### ISSUE TITLE
Other Tutorials

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/learn-redux#13]
Milo wrote this _excellent_ tutorial:
https://medium.com/@bananaoomarang/handcrafting-an-isomorphic-redux-application-with-love-40ada4468af4

and @gaearon's posts on the subject are _very insightful_: https://medium.com/@dan_abramov

originally mentioned on: https://github.com/dwyl/learn-react/issues/4#issuecomment-142269833

**Comment by besarthoxhaj** [comment]
Hi @nelsonic as a learning playground I created this repo https://github.com/besarthoxhaj/middleware-pattern

nothing special, it's just a small implementation of express and redux. I thought it may be useful for others as well.

**Comment by nelsonic** [comment]
@besarthoxhaj looks good. :+1:

**Comment by iteles** [comment]
@sohilpandya I think you were working through a tutorial with @minaorangina that you guys thought was pretty epic too?

**Comment by sohilpandya** [comment]
Oh yeah! @iteles its this one by Teropa. 
http://teropa.info/blog/2015/09/10/full-stack-redux-tutorial.html

Quite a heavy one but definitely worth spending a few days doing it. 😊

**Comment by iteles** [comment]
From @jrans: https://www.youtube.com/playlist?list=PLPgDBCA1Cb3NXTI0Ceqpw3GqXBrv7rjld

**Comment by sohilpandya** [comment]
Another one, really short and cool! https://medium.com/@rajaraodv/step-by-step-guide-to-building-react-redux-apps-using-mocks-48ca0f47f9a#.f5gc5hyjs

**Comment by nelsonic** [comment]
Good share @sohilpandya :+1: 
Read that one yesterday. Its a good summary of the Todo app.
We need to write a more complete example... if only we had _Time_...! :hourglass:

**Comment by ghost** [comment]
Hi, guys! I'm learning React with Redux, in the process I created a kind of tutorial/guide that summarizes my understanding.
Here is the first one, where I setup React with Webpack, generating a simple counter app:
https://gist.github.com/MrOutis/0f8f06e1dcd9f64cdbee

Then, I did the same counter app but implementing Redux for state management. It doesn't show the power of Redux, but there are some useful links and comments.
https://gist.github.com/MrOutis/0f8f06e1dcd9f64cdbee

I read the egghead [notes](https://github.com/dwyl/learn-redux/blob/master/egghead.io_video_tutorial_notes.md) in this repository, the first ones are pretty cool, but the rest turn out to be a transcript of the videos (pretty cool, tho, with syntax highlighting and markdown).
If you find my notes somehow useful, I'd me happy to open some pull requests to integrate them with your feedback.

There's also a [Ducks](https://github.com/erikras/ducks-modular-redux) implementation in mind, and a redux-middleware one. Maybe adding some redux-router explanation would be amazing.

Greetings from México! :beers:

**Comment by nelsonic** [comment]
Redux `->` elm ... https://github.com/dwyl/learn-elm/
