### ISSUE TITLE
Offline Storage for Redux Store?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/learn-redux#19]
Which library should we use to save the Redux `store` locally on the device/browser for offline use.

**Comment by webwelten** [comment]
Hey @nelsonic ,
we're using https://github.com/michaelcontento/redux-storage. 
What have you found so far? Have you already made a decision?

I know there's also:
- https://github.com/elgerlambert/redux-localstorage
- https://github.com/rt2zz/redux-persist
- https://github.com/zackify/redux-restore

**Comment by nelsonic** [comment]
@webwelten thanks for adding those links! feel free to PR them into the main readme! :+1:

**Comment by nelsonic** [comment]
Useful. but this is better: https://github.com/dwyl/learn-elm/issues/36
