### ISSUE TITLE
Can we use Redux with Web Components (or Polymer) ?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/learn-redux#23]
React vs. Web Components Discussion on Redit: 
https://www.reddit.com/r/javascript/comments/3shuzw/react_vs_web_components_what_would_you_do_xpost/

Call me a _luddite_, but I still like the idea of using a **_Web Standard**_ 
(_even one that is only a "Draft"..._) over using a proprietary "_our-way-is-best_" framework...

**Comment by GeoloeG-IsT** [comment]
Check this article for an example with NuclearJS: http://paulusschoutsen.nl/blog/2015/07/using-polymer-with-flux-and-a-global-app-state/

**Comment by nelsonic** [comment]
Good article @MeTaNoV thanks for sharing. :+1:

**Comment by lastmjs** [comment]
I've made a custom element that let's you use Redux declaratively. Just pop the element into any component that needs it: https://github.com/lastmjs/redux-store-element

**Comment by nelsonic** [comment]
Nice work @lastmjs 🎉

**Comment by nelsonic** [comment]
https://github.com/dwyl/learn-elm/

**Comment by bitflower** [comment]
@lastmjs Do you have a sample app using redux-store-element?
