### ISSUE TITLE
Add these articles to repo?

### ISSUE THREAD

**Issue by hdrdavies** [nelsonic/learn-redux#30]
A cartoon to resemble what's going on with Redux:

https://code-cartoons.com/a-cartoon-intro-to-redux-3afb775501a6#.69zpibshk

With a previous example of Flux:

https://code-cartoons.com/a-cartoon-guide-to-flux-6157355ab207#.yzpzp1nai

This really helped me understand what was going on with both frameworks and why Redux is seen as an improvement.

**Comment by hdrdavies** [comment]
Another handy explanation (shorter) of hot loading and time-travel debugging in redux:

https://code-cartoons.com/hot-reloading-and-time-travel-debugging-what-are-they-3c8ed2812f35#.pzbtxql0h

**Comment by nelsonic** [comment]
For _sure_! great links! :+1:

**Comment by iteles** [comment]
Nice!

**Comment by nelsonic** [comment]
huw added articles. :+1:
