### ISSUE TITLE
Getting issue during deployment of nodejs file locally using heroku toolbelt

### ISSUE THREAD

**Issue by soumenpal123** [nelsonic/learn-redux#35]
Hi, I am new to it and am getting below error. Thanks in advance.

C:\Program Files\nodejs>heroku local web
[WARN] No ENV file found
[WARN] ENOENT: no such file or directory, open 'C:\Program Files\nodejs\Procfile
'
[OKAY] package.json file found - trying 'npm start'
9:44:01 AM web.1 | > weathernodejs@1.0.0 start C:\Program Files\nodejs
9:44:01 AM web.1 | > node quickstart.js
9:44:01 AM web.1 | usage: node examples/quickstart.js ORIGDWXKSWGSLKSOT7RQIJLHR
NWMELD2
9:44:01 AM web.1 | npm
9:44:01 AM web.1 | ERR! Windows_NT 6.2.9200
9:44:01 AM web.1 | npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Pro
gram Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
9:44:01 AM web.1 | npm ERR! node v6.4.0
9:44:01 AM web.1 | npm ERR! npm v3.10.3
9:44:01 AM web.1 | npm ERR! code ELIFECYCLE
9:44:01 AM web.1 | npm ERR!
9:44:01 AM web.1 | weathernodejs@1.0.0 start: node quickstart.js
9:44:01 AM web.1 | npm ERR! Exit status 1
9:44:01 AM web.1 | npm ERR!
9:44:01 AM web.1 | npm ERR! Failed at the weathernodejs@1.0.0 start script 'nod
e quickstart.js'.
9:44:01 AM web.1 | npm ERR! Make sure you have the latest version of node.js an
d npm installed.
9:44:01 AM web.1 | npm ERR! If you do, this is most likely a problem with the w
eathernodejs package,
9:44:01 AM web.1 | npm ERR! not with npm itself.
9:44:01 AM web.1 | npm ERR! Tell the author that this fails on your system:
9:44:01 AM web.1 | npm ERR! node quickstart.js
9:44:01 AM web.1 | npm ERR! You can get information on how to open an issue for
this project with:
9:44:01 AM web.1 | npm ERR! npm bugs weathernodejs
9:44:01 AM web.1 | npm ERR! Or if that isn't available, you can get their info
via:
9:44:01 AM web.1 | npm ERR! npm owner ls weathernodejs
9:44:01 AM web.1 | npm ERR! There is likely additional logging output above.
9:44:01 AM web.1 | npm ERR! Please include the following file with any support
request:
9:44:01 AM web.1 | npm ERR! C:\Program Files\nodejs\npm-debug.log
[DONE] Killing all processes with signal null
9:44:01 AM web.1 Exited with exit code 1
# 

And here is the log file:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli 'start' ]
2 info using npm@3.10.3
3 info using node@v6.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle weathernodejs@1.0.0~prestart: weathernodejs@1.0.0
6 silly lifecycle weathernodejs@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle weathernodejs@1.0.0~start: weathernodejs@1.0.0
8 verbose lifecycle weathernodejs@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle weathernodejs@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Program Files\nodejs\node_modules.bin;C:\Program Files\nodejs;"C:\Program Files (x86)\Heroku\ruby-2.1.7\bin";C:\Program Files\Microsoft SDKs\Azure.NET SDK\v2.8\bin;C:\Program Files\Microsoft SDKs\Azure\emulator;C:\Program Files\Microsoft SDKs\Azure\emulator\devstore;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft Office Servers\15.0\Bin\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Heroku\bin;C:\Program Files (x86)\git\cmd;C:\Program Files (x86)\Git\cmd;C:\Program Files\nodejs\;C:\Users\ericame\AppData\Roaming\npm;C:\Program Files (x86)\Git\bin
10 verbose lifecycle weathernodejs@1.0.0~start: CWD: C:\Program Files\nodejs
11 silly lifecycle weathernodejs@1.0.0~start: Args: [ '/d /s /c', 'node quickstart.js' ]
12 silly lifecycle weathernodejs@1.0.0~start: Returned: code: 1 signal: null
13 info lifecycle weathernodejs@1.0.0~start: Failed to exec start script
14 verbose stack Error: weathernodejs@1.0.0 start: node quickstart.js
14 verbose stack Exit status 1
14 verbose stack at EventEmitter. (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack at emitTwo (events.js:106:13)
14 verbose stack at EventEmitter.emit (events.js:191:7)
14 verbose stack at ChildProcess. (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack at emitTwo (events.js:106:13)
14 verbose stack at ChildProcess.emit (events.js:191:7)
14 verbose stack at maybeClose (internal/child_process.js:852:16)
14 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid weathernodejs@1.0.0
16 verbose cwd C:\Program Files\nodejs
17 error Windows_NT 6.2.9200
18 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
19 error node v6.4.0
20 error npm v3.10.3
21 error code ELIFECYCLE
22 error weathernodejs@1.0.0 start: node quickstart.js
22 error Exit status 1
23 error Failed at the weathernodejs@1.0.0 start script 'node quickstart.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the weathernodejs package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error node quickstart.js
23 error You can get information on how to open an issue for this project with:
23 error npm bugs weathernodejs
23 error Or if that isn't available, you can get their info via:
23 error npm owner ls weathernodejs
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by soumenpal123** [comment]
I am able to resolve the issue after making some changes into my quickstart.js file.
But in quickstart.js file if I put below code:
const client = new Wit(token, actions);
client.interactive();

I am below issue:

[OKAY] package.json file found - trying 'npm start'
12:44:52 PM web.1 |  > weathernodejs@1.0.0 start C:\Program Files\nodejs
12:44:52 PM web.1 |  > node quickstart.js
12:44:52 PM web.1 |  >
12:44:52 PM web.1 |  string_decoder.js:71
12:44:52 PM web.1 |    if (buf.length === 0)
12:44:52 PM web.1 |           ^
12:44:52 PM web.1 |  TypeError: Cannot read property 'length' of null
12:44:52 PM web.1 |      at StringDecoder.write (string_decoder.js:71:10)
12:44:52 PM web.1 |      at Interface._normalWrite (readline.js:343:30)
12:44:52 PM web.1 |      at Interface.write (readline.js:334:49)
12:44:52 PM web.1 |      at interactive (C:\Program Files\nodejs\node-wit\lib\wi
t.js:289:13)
12:44:52 PM web.1 |      at Object.<anonymous> (C:\Program Files\nodejs\quicksta
rt.js:97:8)
12:44:52 PM web.1 |      at Module._compile (module.js:556:32)
12:44:52 PM web.1 |      at Object.Module._extensions..js (module.js:565:10)
12:44:52 PM web.1 |      at Module.load (module.js:473:32)
12:44:52 PM web.1 |      at tryModuleLoad (module.js:432:12)
12:44:52 PM web.1 |      at Function.Module._load (module.js:424:3)
12:44:52 PM web.1 |  npm
12:44:52 PM web.1 |   ERR! Windows_NT 6.2.9200
12:44:52 PM web.1 |  npm ERR!
12:44:52 PM web.1 |   argv "C:\Program Files\nodejs\node.exe" "C:\Program Fi
les\nodejs\node_modules\npm\bin\npm-cli.js" "start"
12:44:52 PM web.1 |  npm ERR! node v6.4.0
12:44:52 PM web.1 |  npm ERR! npm  v3.10.3
12:44:52 PM web.1 |  npm ERR! code ELIFECYCLE
12:44:52 PM web.1 |  npm ERR! weathernodejs@1.0.0 start: `node quickstart.js`
12:44:52 PM web.1 |  npm ERR! Exit status 1
12:44:52 PM web.1 |  npm ERR!
12:44:52 PM web.1 |  npm ERR! Failed at the weathernodejs@1.0.0 start script 'no
de quickstart.js'.
12:44:52 PM web.1 |  npm ERR! Make sure you have the latest version of node.js a
nd npm installed.
12:44:52 PM web.1 |  npm ERR! If you do, this is most likely a problem with the
weathernodejs package,
12:44:52 PM web.1 |  npm ERR! not with npm itself.
12:44:52 PM web.1 |  npm ERR! Tell the author that this fails on your system:
12:44:52 PM web.1 |  npm ERR!     node quickstart.js
12:44:52 PM web.1 |  npm ERR! You can get information on how to open an issue fo
r this project with:
12:44:52 PM web.1 |  npm ERR!     npm bugs weathernodejs
12:44:52 PM web.1 |  npm ERR! Or if that isn't available, you can get their info
 via:
12:44:52 PM web.1 |  npm
12:44:52 PM web.1 |   ERR!     npm owner ls weathernodejs
12:44:52 PM web.1 |  npm ERR! There is likely additional logging output above.
12:44:52 PM web.1 |  npm
12:44:52 PM web.1 |   ERR! Please include the following file with any support re
quest:
12:44:52 PM web.1 |  npm ERR!     C:\Program Files\nodejs\npm-debug.log
[DONE] Killing all processes with signal  null
12:44:52 PM web.1 Exited with exit code 1

**Comment by soumenpal123** [comment]
Can anyone please answer why I am getting above issue executing the below code:

const client = new Wit(token, actions);

client.interactive();

**Comment by nelsonic** [comment]
Hi @soumenpal123, the task that you are trying to accomplish does not _appear_ to be related to purpose of this repository (_learning how to use the `redux` library_) ... please raise this issue on the heroku toolbelt issues instead: https://github.com/heroku/cli/issues

_Thanks_!
