### ISSUE TITLE
What does the exclamation mark do before the function?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/learn-redux#4]
When reading the source of (_of the_ **_minified**_ _version of_) **Redux** https://cdnjs.cloudflare.com/ajax/libs/redux/3.0.5/redux.min.js you will see: `!function(t,e)` this is to save a byte... http://stackoverflow.com/a/5654929/1148249

**Comment by nelsonic** [comment]
Need a better way of storing these kinds of questions/answers ...

**Comment by niketpathak** [comment]
Yeah, true that! Although, there are a lot of blogs that explains it in detail. This article @[Digital Fortress](http://digitalfortress.tech/js/exclamation-mark-function-iife/) may help others too!
