### ISSUE TITLE
Please Correct link

### ISSUE THREAD

**Issue by kaoussi** [nelsonic/learn-redux#44]
The official Redux github repository link is linking to the wrong repo.

**Comment by newswim** [comment]
You're right! It's currently pointed at https://github.com/rackt/redux, but it should be https://github.com/reactjs/redux

if you want to, feel free to open a PR to make this change. If you need a refresher on that, check out the [contributing repo](https://github.com/dwyl/contributing). If you have any other questions, feel free to ask :-)
