### ISSUE TITLE
Link: Build Yourself A Redux

### ISSUE THREAD

**Issue by newswim** [nelsonic/learn-redux#45]
Pretty great tutorial from Zapier! Remeniscent of stuff like [Build Yourself A Scheme (in 48 hours)](https://en.wikibooks.org/wiki/Write_Yourself_a_Scheme_in_48_Hours).

**Comment by nelsonic** [comment]
Great link/tutorial! Let's add this link! (_if you have time to PR please go for it!_) 👍

**Comment by newswim** [comment]
Oops. I did a no-no and committed directly to master, I thought editing the readme would have initiated a PR (it does on repos where you don't have write access).

My apologies, I know this is not good practice. But, the link is added 😅
