### ISSUE TITLE
How long do the Egghead.io Redux Videos Take (Total Elapsed Time)?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/learn-redux#51]
I'm _busy_ writing a post on how _long_ it takes to learn React, Redux, Immutable.js, Flow etc.
So, I need to know what the **_total_ running time** is for the videos.

The duration of each video is shown next to the clock icon in the list of videos:
https://egghead.io/lessons/javascript-redux-the-single-immutable-state-tree
![image](https://user-images.githubusercontent.com/194400/30908329-32429062-a375-11e7-9763-8d0e85e7d945.png)

I could sit and _manually_ add them up using mental arithmetic (_or a calculator_).
But where's the _fun_ in that?

**Comment by nelsonic** [comment]
## Script

```javascript
  var len = document.getElementsByClassName('index__clockIcon__3s3nE').length; // number of vids
  var sum = 0;
  for(var i = 0; i < len; i++){
    var parts = document.getElementsByClassName('index__clockIcon__3s3nE')[0]
      .nextElementSibling.innerHTML.split(":"); // time value is next DOM element to the clock icon.
    var m = parseInt(parts[0], 10) * 60; // multiply the minute figure by 60 sec.
    var s = parseInt(parts[1], 10);
    sum = sum + m + s;
  }
console.log(sum / 60); // we accumulated the time in seconds so divide by 60. ;-)
```
![image](https://user-images.githubusercontent.com/194400/30909217-3c9b076c-a378-11e7-8491-7ff329ffc6da.png)

## Result: *66 minutes*

Note: you _can_ alter the playback speed to **1.5** or even ***double*** speed.
But I _highly_ doubt a _complete_ beginner is going to do that and still actually _learn_ anything! 🙄

**Comment by deadcoder0904** [comment]
Fun fact - Egghead teaches about Development & Security & its own website isn't secure.

Anyone can download their videos for free using [youtube-dl](https://github.com/rg3/youtube-dl)

`youtube-dl https://egghead.io/courses/getting-started-with-redux`

When I told them, there was no response 😞

**Comment by nelsonic** [comment]
@deadcoder0904 Yeah, I _suspect_ they are making "_enough_" money to _not_ care if people download. 🤔 
(_I downloaded the videos when I was learning so I could watch them offline ..._)

> Good on you for _reporting_ it to them. 👍

**Comment by newswim** [comment]
![wow](https://media.giphy.com/media/l3q2K5jinAlChoCLS/giphy.gif)

Wow. Incredible that they didn't do anything.. but yeah, good on you for reporting it!

@nelsonic, it looks like they add the runtime for each course

<img width="791" alt="screen shot 2017-09-27 at 3 20 57 pm" src="https://user-images.githubusercontent.com/6667096/30936171-9db6f9b4-a398-11e7-891b-50e5dfa68133.png">
